export const copy = {
  en: {
    nav: ['Calculator', 'How it works', 'The extension', 'Support'], install: 'Add to Chrome', free: 'Free. No account needed.',
    eyebrow: 'A LITTLE PERSPECTIVE BEFORE YOU BUY', title: 'The price is once.', titleAccent: 'The value is every day.',
    intro: 'A great purchase earns its place in your life. See what each use could cost before you make it yours.',
    local: 'Calculated on your device', open: 'Free & open source', cue: 'PUT YOUR NEXT PURCHASE IN PERSPECTIVE',
    calc: 'Is it worth it?', calcSub: 'Start with an example. Make the numbers yours.', examples: ['Headphones', 'Everyday shoes', 'Coffee machine'],
    product: 'What are you considering?', price: 'Purchase price', currency: 'Currency', duration: 'How long will you keep it?', years: 'years',
    frequency: 'Uses per week', useHint: 'Be honest. A realistic estimate is more useful than an optimistic one.', advanced: 'Resale, maintenance & installments',
    resale: 'Estimated resale value', maintenance: 'Total maintenance cost', payments: 'Number of installments', totalPaid: 'Total paid with installments',
    advancedHelp: 'Maintenance is for the full ownership period. When installments are entered, their total replaces the purchase price.',
    result: 'YOUR ESTIMATED COST', perUse: 'per use', uses: 'estimated uses', net: 'net cost', period: 'over {years} years',
    less: 'What if you use it half as much?', half: 'Half the use', expected: 'Expected use', scenario: 'Same ownership period and net cost. Only usage changes.',
    target: 'Make it worth it to you.', targetLabel: 'Your target per use (optional)', targetResult: '{uses} total uses to reach your target.',
    enough: 'Your estimated usage would reach this target.', more: 'That’s {uses} more uses than you estimated.', targetInvalid: 'Enter a positive target that gives a practical number of uses.',
    empty: 'Enter valid numbers to see your estimate.', invalid: 'Use a positive price, ownership period and usage. Costs must be non-negative, and resale cannot exceed total cost.',
    usesInvalid: 'This estimate rounds to fewer than one use. Increase the period or frequency.',
    disclaimer: 'An estimate, not a verdict. Your budget, needs and actual use matter too.',
    methodTag: 'LESS GUESSWORK. MORE PERSPECTIVE.', methodTitle: 'A small calculation.\nA clearer decision.',
    steps: [ ['01', 'Start with the real cost.', 'Take the purchase price, add maintenance or financing costs, and subtract what you expect to resell it for.'], ['02', 'Think about your everyday.', 'Estimate how often you will use it and how long you will keep it. Give yourself room to be realistic.'], ['03', 'Find your own “worth it.”', 'Divide the net cost by expected uses. Try a lower-use scenario, or set a cost-per-use target that works for you.'] ],
    equation: ['Net cost', 'Expected uses', 'Cost per use'],
    extensionTag: 'A SECOND THOUGHT, ONE CLICK AWAY', extensionTitle: 'Take the calculator\nshopping with you.',
    extensionText: 'Open Cost Per Use right on a product page. Optional autofill reads the product details, so you can spend less time entering numbers and more time thinking about the purchase.',
    bullets: ['Compare up to three products', 'Keep calculations in your browser', 'Available in ten languages'],
    extensionNote: 'For Chrome on desktop. The calculator above works on your phone, too.',
    faqTitle: 'A few good questions.', faqs: [
      ['What is cost per use?', 'It is the net cost of a purchase divided by the number of times you expect to use it. A $200 purchase used 400 times costs $0.50 per use.'],
      ['Does a low cost per use mean I should buy it?', 'Not necessarily. It is one way to compare purchases, not a measure of everything that matters. Consider your budget, your needs, and whether you already own something that does the job.'],
      ['Where do my numbers go?', 'This website calculates in your browser and does not save or send your calculator inputs. The extension can save calculations locally in your browser. Our site host processes normal requests needed to serve the website.'],
      ['Do I need to install anything?', 'No. Use this calculator here, on desktop or mobile. The free Chrome extension adds product-page autofill, comparison and local history.'] ],
    footer: 'Buy thoughtfully. Use happily.', source: 'Source code', support: 'Help & feedback', privacy: 'Extension privacy policy',
  },
  tr: {
    nav: ['Hesaplayıcı', 'Nasıl çalışır?', 'Eklenti', 'Destek'], install: 'Chrome’a ekle', free: 'Ücretsiz. Hesap gerekmez.',
    eyebrow: 'SATIN ALMADAN ÖNCE KÜÇÜK BİR BAKIŞ AÇISI', title: 'Fiyatı bir kez.', titleAccent: 'Değeri her gün.',
    intro: 'İyi bir alışveriş hayatınızda yerini hak eder. Satın almadan önce her kullanımın ne kadara mal olabileceğini görün.',
    local: 'Cihazınızda hesaplanır', open: 'Ücretsiz ve açık kaynak', cue: 'BİR SONRAKİ ALIŞVERİŞİNİZE YENİ BİR GÖZLE BAKIN',
    calc: 'Değer mi?', calcSub: 'Bir örnekle başlayın. Rakamları kendinize uyarlayın.', examples: ['Kulaklık', 'Günlük ayakkabı', 'Kahve makinesi'],
    product: 'Ne almayı düşünüyorsunuz?', price: 'Satın alma fiyatı', currency: 'Para birimi', duration: 'Ne kadar süre kullanacaksınız?', years: 'yıl',
    frequency: 'Haftalık kullanım', useHint: 'Gerçekçi olun. Gerçekçi bir tahmin, iyimser bir tahminden daha faydalıdır.', advanced: 'Yeniden satış, bakım ve taksitler',
    resale: 'Tahmini yeniden satış değeri', maintenance: 'Toplam bakım maliyeti', payments: 'Taksit sayısı', totalPaid: 'Taksitlerle ödenen toplam',
    advancedHelp: 'Bakım, tüm sahiplik süresini kapsar. Taksit girildiğinde toplam ödeme, satın alma fiyatının yerini alır.',
    result: 'TAHMİNİ MALİYETİNİZ', perUse: 'kullanım başına', uses: 'tahmini kullanım', net: 'net maliyet', period: '{years} yıl boyunca',
    less: 'Yarı yarıya kullanırsanız?', half: 'Yarı yarıya kullanım', expected: 'Beklenen kullanım', scenario: 'Sahiplik süresi ve net maliyet aynı. Yalnızca kullanım değişir.',
    target: 'Sizin için değerli olsun.', targetLabel: 'Kullanım başına hedefiniz (isteğe bağlı)', targetResult: 'Hedefinize ulaşmak için toplam {uses} kullanım.',
    enough: 'Tahmini kullanımınız bu hedefe ulaşmaya yeterli.', more: 'Bu, tahmininizden {uses} kullanım daha fazla.', targetInvalid: 'Hesaplanabilir bir kullanım sayısı veren pozitif bir hedef girin.',
    empty: 'Tahmini görmek için geçerli değerler girin.', invalid: 'Fiyat, süre ve kullanım pozitif olmalı. Maliyetler negatif olamaz; yeniden satış toplam maliyeti aşamaz.',
    usesInvalid: 'Bu tahmin birden az kullanıma yuvarlanıyor. Süreyi veya kullanım sıklığını artırın.',
    disclaimer: 'Bu bir tahmin, karar değil. Bütçeniz, ihtiyaçlarınız ve gerçek kullanımınız da önemli.',
    methodTag: 'DAHA AZ TAHMİN. DAHA NET BİR BAKIŞ.', methodTitle: 'Küçük bir hesap.\nDaha net bir karar.',
    steps: [ ['01', 'Gerçek maliyetle başlayın.', 'Satın alma fiyatına bakım veya finansman maliyetlerini ekleyin; tahmini yeniden satış değerini çıkarın.'], ['02', 'Günlük hayatınızı düşünün.', 'Ne sıklıkla ve ne kadar süre kullanacağınızı tahmin edin. Gerçekçi olmaya özen gösterin.'], ['03', 'Sizin için “değer” olanı bulun.', 'Net maliyeti tahmini kullanıma bölün. Daha az kullanım senaryosunu deneyin veya kendinize bir hedef belirleyin.'] ],
    equation: ['Net maliyet', 'Tahmini kullanım', 'Kullanım başına maliyet'],
    extensionTag: 'BİR TIKLA YENİDEN DÜŞÜNÜN', extensionTitle: 'Hesaplayıcınızı\nalışverişe götürün.',
    extensionText: 'Cost Per Use’u ürün sayfasında açın. İsteğe bağlı otomatik doldurma ürün bilgilerini okur; rakam girmek yerine alışverişinizi değerlendirmeye zaman ayırın.',
    bullets: ['Üç ürüne kadar karşılaştırın', 'Hesaplamaları tarayıcınızda saklayın', 'On dilde kullanın'],
    extensionNote: 'Masaüstü Chrome için. Yukarıdaki hesaplayıcı telefonunuzda da çalışır.',
    faqTitle: 'Birkaç iyi soru.', faqs: [
      ['Kullanım başına maliyet nedir?', 'Bir ürünün net maliyetinin tahmini kullanım sayısına bölünmesidir. 200 ₺ tutarında bir ürün 400 kez kullanıldığında kullanım başına maliyeti 0,50 ₺ olur.'],
      ['Düşük maliyet ürünü almam gerektiğini mi gösterir?', 'Her zaman değil. Bu, alışverişleri karşılaştırmanın bir yoludur. Bütçenizi, ihtiyaçlarınızı ve aynı işi yapan bir ürüne zaten sahip olup olmadığınızı düşünün.'],
      ['Girdiğim bilgiler nereye gider?', 'Bu site hesaplamaları tarayıcınızda yapar; hesaplama girdilerinizi kaydetmez veya göndermez. Eklenti hesaplamaları tarayıcınızda yerel olarak saklayabilir. Site sağlayıcımız, siteyi sunmak için gereken normal istekleri işler.'],
      ['Bir şey yüklemem gerekiyor mu?', 'Hayır. Bu hesaplayıcıyı bilgisayarınızda veya telefonunuzda kullanabilirsiniz. Ücretsiz Chrome eklentisi ürün bilgilerini otomatik doldurma, karşılaştırma ve yerel geçmiş özelliklerini ekler.'] ],
    footer: 'Düşünerek alın. Keyifle kullanın.', source: 'Kaynak kodu', support: 'Yardım ve geri bildirim', privacy: 'Eklenti gizlilik politikası',
  },
};
